#! /usr/bin/env bash

git submodule update --init --recursive
cat <<EOF > library/dependencies/ffmpeg/libavutil/avconfig.h
/* Generated by ffconf */
#ifndef AVUTIL_AVCONFIG_H
#define AVUTIL_AVCONFIG_H
#define AV_HAVE_BIGENDIAN 0
#define AV_HAVE_FAST_UNALIGNED 0
#endif /* AVUTIL_AVCONFIG_H */
EOF

export NDK_DIR="$ANDROID_HOME/ndk/25.1.8937393"
[[ -d $NDK_DIR ]] || {
	echo "NDK not found at $NDK_DIR"
	exit 1
}
(
	cd library
	sh build_ffmpeg.sh --clear
	sh build_ffmpeg.sh --init
	sh build_ffmpeg.sh
	sh build_ffmpeg.sh --update
)

./gradlew clean
./gradlew :library:build

cp library/build/outputs/aar/library-release.aar libgdx-oboe.aar

